services:
  backend:
    build:
      context: ./backend             
      dockerfile: Dockerfile          
    ports:
      - "5000:5000"                 
    volumes:
      - ./backend/instance:/app/instance  
    environment:
      - FLASK_ENV=development


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
     - NODE_ENV=production
